import { ref, set } from "firebase/database";
import { database } from "@/lib/firebaseConfig";
import { NextApiRequest, NextApiResponse } from "next";


export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const doctorRef = ref(database, "doctors");
 await set(doctorRef, {
    1: {
      id: 1,
      doctorId: "PK-1001",
      name: "Dr. Ahsan Ali",
      email: "ahsan.ali@hospital.pk",
      photo: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0300-1234567",
      speciality: ["Ophthalmology"],
      schedule: ["Mon AM", "Wed PM", "Fri AM"],
      address: "Gulshan-e-Iqbal, Karachi, Pakistan",
    },
    2: {
      id: 2,
      doctorId: "PK-1002",
      name: "Dr. Sana Khalid",
      email: "sana.khalid@medcare.pk",
      photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0311-2345678",
      speciality: ["Dermatology", "Pediatrics"],
      schedule: ["Tue AM", "Thu PM"],
      address: "F-8 Sector, Islamabad, Pakistan",
    },
    3: {
      id: 3,
      doctorId: "PK-1003",
      name: "Dr. Usman Javed",
      email: "usman.javed@neuroclinic.pk",
      photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0333-7654321",
      speciality: ["Neurology"],
      schedule: ["Mon PM", "Wed AM"],
      address: "Model Town, Lahore, Pakistan",
    },
    4: {
      id: 4,
      doctorId: "PK-1004",
      name: "Dr. Zara Ahmed",
      email: "zara.ahmed@ortho.pk",
      photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0345-9876543",
      speciality: ["Orthopedics"],
      schedule: ["Tue AM", "Fri PM"],
      address: "Cantt Area, Multan, Pakistan",
    },
    5: {
      id: 5,
      doctorId: "PK-1005",
      name: "Dr. Hira Siddiqui",
      email: "hira.siddiqui@mindcare.pk",
      photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0301-1112233",
      speciality: ["Psychiatry", "Internal Medicine"],
      schedule: ["Wed PM", "Sat AM"],
      address: "Satellite Town, Rawalpindi, Pakistan",
    },
    6: {
      id: 6,
      doctorId: "PK-1006",
      name: "Dr. Kamran Farooq",
      email: "kamran.farooq@radioclinic.pk",
      photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0322-5566778",
      speciality: ["Radiology"],
      schedule: ["Mon AM", "Thu PM"],
      address: "University Road, Peshawar, Pakistan",
    },
    7: {
      id: 7,
      doctorId: "PK-1007",
      name: "Dr. Nimra Qureshi",
      email: "nimra.q@entpk.com",
      photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0308-9098765",
      speciality: ["ENT", "Pulmonology"],
      schedule: ["Tue PM", "Thu AM"],
      address: "Jinnah Road, Quetta, Pakistan",
    },
    8: {
      id: 8,
      doctorId: "PK-1008",
      name: "Dr. Areeba Khan",
      email: "areeba.khan@hormoncare.pk",
      photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0340-2233445",
      speciality: ["Nephrology", "Endocrinology"],
      schedule: ["Wed AM", "Sat PM"],
      address: "North Nazimabad, Karachi, Pakistan",
    },
    9: {
      id: 9,
      doctorId: "PK-1009",
      name: "Dr. Bilal Rafiq",
      email: "bilal.rafiq@gutclinic.pk",
      photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0313-4445566",
      speciality: ["Gastroenterology", "Urology"],
      schedule: ["Mon PM", "Fri AM"],
      address: "DHA Phase 2, Karachi, Pakistan",
    },
    10: {
      id: 10,
      doctorId: "PK-1010",
      name: "Dr. Fawad Khan",
      email: "fawad.khan@cancerclinic.pk",
      photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "0302-6655443",
      speciality: ["Oncology"],
      schedule: ["Thu PM", "Sat AM"],
      address: "Johar Town, Lahore, Pakistan",
    },
  });
  res.status(200).json({ message: "Doctors seeded" });
}
